find_route/urls.py
from django.contrib import admin
from django.urls import path, include

from routes.views import (
    home, find_routes, add_route, save_route, RoutesViewList, RouteDetailView
)


urlpatterns = [
    path('admin/', admin.site.urls),

    # path('', include('main.urls')),
    path('cities/', include('cities.urls')),
    path('trains/', include('trains.urls')),
    path('accounts/', include('accounts.urls')),
    # path('routes/', include('routes.urls')),
    path('', home, name='home'),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('save_route/', save_route, name='save_route'),
    path('list_routes/', RoutesViewList.as_view(), name='list_routes'),
    path('detail_route/<int:pk>/', RouteDetailView.as_view(), name='detail_route'),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
]

trains/urls.py
from django.urls import path, include
from . import views
from .views import *
# TrainListView, TrainDetailView, TrainCreateView, TrainUpdateView, TrainDeleteView

app_name = "trains"

urlpatterns = [
    path('', TrainListView.as_view(), name="trains"),
    path('<int:pk>/', TrainDetailView.as_view(), name="detail"),
    path('create/', TrainCreateView.as_view(), name="create"),
    path('<int:pk>/update/', TrainUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', TrainDeleteView.as_view(), name="delete"),
    # path('', views.trains, name="trains"),
]

trains/models.py
from django.core.exceptions import ValidationError
from django.db import models
from cities.models import City


class Train(models.Model):
    """Задаем поля в таблице: имя, время_в_пути, город_отправления и город_назначения"""
    name = models.CharField(max_length=50, unique=True, verbose_name="Номер поезда")
    travel_time = models.PositiveSmallIntegerField(verbose_name="Время в пути")

    departure_city = models.ForeignKey(City, on_delete=models.CASCADE,  # CASCADE - Приудалении данных в одной таблице удаляются и связанные данные в др. таблицах
                                       # null=True, blank=True,
                                       related_name="departure_city_set",  # Указание имени для набора (множества) экземпляров класса Train
                                       verbose_name="Город отправления"
                                       )
    destination_city = models.ForeignKey("cities.City", on_delete=models.CASCADE,  # К модели City можно обратиться не только импортировав такую модель,
                                         related_name="destination_city_set",  # from .. import City, но и указав напрямую название приложения и имя модели
                                         verbose_name="Город назначения"
                                         )

    def __str__(self):
        return f'Поезд {self.name} из города {self.departure_city} в город {self.destination_city}'

    class Meta:
        verbose_name = "Поезд"
        verbose_name_plural = "Поезда"
        ordering = ["travel_time"]

    def clean(self):
        """В данной функции мы проверяем уникальность новой записи и поднимаем ошибку в случае, если запись не уникальна"""
        if self.departure_city == self.destination_city:
            raise ValidationError("Города отправления и назначения должны отличаться")
        qs = Train.objects.filter(departure_city=self.departure_city,
                                  destination_city=self.destination_city,
                                  travel_time=self.travel_time,
                                  ).exclude(pk=self.id)
        # Запись Train аналогична записи self.__class__
        if qs.exists():
            raise ValidationError("Изменить время в пути")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

trains/forms.py
from django import forms
from trains.models import Train
from cities.models import City


class TrainForm(forms.ModelForm):
    name = forms.CharField(label="Поезд",
                           widget=forms.TextInput(attrs={
                               "class": "form-control",
                               "placeholder": "Введите название поезда"
                           }))

    travel_time = forms.IntegerField(label="Время в пути",
                                     widget=forms.NumberInput(attrs={
                                           "class": "form-control",
                                           "placeholder": "Укажите время в пути"
                                     }))  # forms.ImageField - неверный формат ввода данных

    departure_city = forms.ModelChoiceField(label="Город отправления",
                                            queryset=City.objects.all(),
                                            widget=forms.Select(attrs={
                                                "class": "form-control",
                                            }))

    destination_city = forms.ModelChoiceField(label="Город назначения",
                                              queryset=City.objects.all(),
                                              widget=forms.Select(attrs={
                                                  "class": "form-control",
                                              }))

    class Meta:
        model = Train
        fields = "__all__"  # "name", "travel_time", "departure_city", "destination_city"

trains/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import (DetailView, CreateView, UpdateView, DeleteView, ListView)
from trains.forms import TrainForm
from trains.models import Train

__all__ = (
    "TrainDetailView",
    "TrainCreateView",
    "TrainUpdateView",
    "TrainDeleteView",
    "TrainListView",
)

# def trains(request, page_number=None, pk=None):
#     qs = Train.objects.all()
#     list = Paginator(qs, 4)
#     page_number = request.GET.get('page')
#     page_obj = list.get_page(page_number)
#     data = {
#         "title": "Список Поездов",
#         "page_obj": page_obj,
#             }
#
#     return render(request, "trains/trains.html", data)


class TrainListView(ListView):
    paginate_by = 4
    model = Train
    template_name = "trains/trains.html"


class TrainDetailView(DetailView):
    queryset = Train.objects.all()
    template_name = "trains/detail.html"


class TrainCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Train
    form_class = TrainForm
    template_name = "trains/create.html"
    success_url = reverse_lazy("trains:trains")  # Заменяет def get_absolute_url в models.py
    success_message = "Поезд успешно добавлен"


class TrainUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Train
    form_class = TrainForm
    template_name = "trains/update.html"
    success_url = reverse_lazy("trains:trains")
    success_message = "Поезд успешно отредактирован"


class TrainDeleteView(LoginRequiredMixin, DeleteView):
    model = Train
    template_name = "trains/delete.html"
    success_url = reverse_lazy("trains:trains")

    def get(self, request, *args, **kwargs):
        messages.success(request, "Поезд успешно удален")  # Удаление объекта без перехода на
        return self.post(request, *args, **kwargs)  # соответствующую страницу html и подтверждения

trains/templates/trains/create.html
{% extends 'main/base.html' %}
{% block title %} Создание поезда {% endblock %}

{% block content %}
    <h3>Создание поезда</h3>

    {% include "main/form.html" with button="Добавить новый поезд" %}

{% endblock %}

trains/templates/trains/delete.html
{% extends 'main/base.html' %}
{% block title %} Удаление города {% endblock %}

{% block content %}
    <h3>Удаление города</h3>
    <p>{{ object }}</p>

    <div class="row">
        <div class="col-md-4">
            <form action="{{action}}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-danger">Да, удалить</button>
            </form>
        </div>
    </div>

{% endblock %}

trains/templates/trains/detail.html
{% extends 'main/base.html' %}

{% block title %} Детали о поезде {% endblock %}

{% block content %}
    <h3>Поезд</h3>
    <div class="row">
        <div class="col-md-8 my-3">
            <table class="table table-striped">
                <tr>
                    <th>Номер</th>
                    <th>Откуда</th>
                    <th>Куда</th>
                    <th>Время в пути</th>
                </tr>
                <tr>
                    <td>{{object.name}}</td>
                    <td>{{object.departure_city}}</td>
                    <td>{{object.destination_city}}</td>
                    <td>{{object.travel_time}}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'trains:trains' %}">
                <button type="button" class="btn btn-outline-primary">Назад к списку</button>
            </a>
        </div>
    </div>

{% endblock %}

trains/templates/trains/details.html
{% extends 'main/base.html' %}

{% block title %} Детали о поезде {% endblock %}

{% block content %}
    <h3>Поезд</h3>
    <div class="row">
        <div class="col-md">
            <table class="table table-striped">
                <tr>
                    <th>Номер</th>
                    <th>Откуда</th>
                    <th>Куда</th>
                    <th>Время в пути</th>
                </tr>
                <tr>
                    <td>{{object.name}}</td>
                    <td>{{object.departure_city}}</td>
                    <td>{{object.destination_city}}</td>
                    <td>{{object.travel_time}}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'trains' %}">
                <button type="button" class="btn btn-light">Назад к списку</button>
            </a>
        </div>
    </div>

{% endblock %}

trains/templates/trains/trains.html
{% extends 'main/base.html' %}

{% block title %} Поезда {% endblock %}

{% block content %}
    <h3 align="center">Список поездов</h3>
    {# Отображение списка поездов #}
    <div class="row">
        <div class="col-md-8 mx-auto my-3">
            <table class="table table-striped">
                <tr>
                    <th>Номер</th>
                    <th>Откуда</th>
                    <th>Куда</th>
                    <th>Время в пути</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
                {% for object in page_obj %}
                    <tr>
                        <td><a href="{% url 'trains:detail' pk=object.id %}" style="text-decoration:none">{{object.name}}</a></td>
                        <td>{{object.departure_city}}</td>
                        <td>{{object.destination_city}}</td>
                        <td>{{object.travel_time}}</td>
                        {% if user.is_authenticated %}
                            <td><a href="{% url 'trains:update' pk=object.id %}">
                                <button type="submit" class="btn btn-outline-primary">Редактировать</button></a>
                            </td>
                            <td><a href="{% url 'trains:delete' pk=object.id %}">
                                <button type="submit" class="btn btn-outline-danger">Удалить</button></a>
                            </td>
                        {% else %}
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    {# Пагинация #}
    {% include 'main/pagination.html' %}
{% endblock %}

trains/templates/trains/update.html
{% extends 'main/base.html' %}
{% block title %} Редактирование поезда {% endblock %}

{% block content %}
    <h3>Редактирование поезда</h3>

    {% include "main/form.html" with button="Редактировать" %}

{% endblock %}