cities/urls.py
from django.urls import path, include
from . import views
from .views import *
# CityDetailView, CityCreateView, CityUpdateView, CityDeleteView, CityListView

app_name = "cities"

urlpatterns = [
    # path('', views.cities, name="cities"),
    path('', CityListView.as_view(), name="cities"),
    path('<int:pk>/', CityDetailView.as_view(), name="detail"),
    path('create/', CityCreateView.as_view(), name="create"),
    path('<int:pk>/update/', CityUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', CityDeleteView.as_view(), name="delete"),
]

find_route/urls.py
from django.contrib import admin
from django.urls import path, include

from routes.views import (
    home, find_routes, add_route, save_route, RoutesViewList, RouteDetailView
)


urlpatterns = [
    path('admin/', admin.site.urls),

    # path('', include('main.urls')),
    path('cities/', include('cities.urls')),
    path('trains/', include('trains.urls')),
    path('accounts/', include('accounts.urls')),
    # path('routes/', include('routes.urls')),
    path('', home, name='home'),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('save_route/', save_route, name='save_route'),
    path('list_routes/', RoutesViewList.as_view(), name='list_routes'),
    path('detail_route/<int:pk>/', RouteDetailView.as_view(), name='detail_route'),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
]

cities/models.py
from django.db import models
from django.urls import reverse


class City(models.Model):
    """Задает поле в таблице"""
    name = models.CharField(max_length=128, unique=True, verbose_name="Город",)

    def __str__(self):
        """В таблицах меняет обозначение объекта с city.object(id) на имя собственное объекта"""
        return self.name

    class Meta:
        """Задает название ед. и множ. числа элементов в таблице и принцип сортировки"""
        verbose_name = "Город"
        verbose_name_plural = "Города"
        ordering = ["name"]  # Сортировка объектов таблицы по имени

    def get_absolute_url(self):
        return reverse("detail", kwargs={"pk": self.pk})

cities/forms.py
from django import forms
from .models import City


class HtmlForm(forms.Form):
    name = forms.CharField(label="Город")


class CityForm(forms.ModelForm):
    name = forms.CharField(label="Город", widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Введите название города"
    }))

    class Meta:
        model = City
        fields = ("name",)

cities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView

from .forms import CityForm
from .models import City


__all__ = (
    "CityListView", "CityDetailView", "CityCreateView", "CityUpdateView", "CityDeleteView",
)


class CityListView(ListView):
    paginate_by = 4
    model = City
    template_name = "cities/cities.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = CityForm()
        context["form"] = form
        return context


class CityDetailView(DetailView):
    queryset = City.objects.all()
    template_name = "cities/detail.html"


class CityCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):  # Требуется аутентификация
    model = City
    form_class = CityForm
    template_name = "cities/create.html"
    success_url = reverse_lazy("cities:cities")  # Заменяет def get_absolute_url в models.py
    success_message = "Город успешно добавлен"


class CityUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = City
    form_class = CityForm
    template_name = "cities/update.html"
    success_url = reverse_lazy("cities:cities")
    success_message = "Город успешно отредактирован"


class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = City
    template_name = "cities/delete.html"
    success_url = reverse_lazy("cities:cities")

cities/templates/cities/cities.html
{% extends 'main/base.html' %}

{% block title %} Города {% endblock %}

{% block content %}
    <h3 align="center">Список городов</h3>
    {# Отображение списка городов #}
    <div class="row">
        <div class="col-md-8 mx-auto my-3">
            <table class="table table-striped">
                {% for object in page_obj %}
                    <tr>
                        <td><a href="{% url 'cities:detail' pk=object.id %}" style="text-decoration:none">{{object.name}}</a></td>
                        {% if user.is_authenticated %}
                            <td><a href="{% url 'cities:update' pk=object.id %}">
                                <button type="submit" class="btn btn-outline-primary">Редактировать</button></a></td>
                            <td><a href="{% url 'cities:delete' pk=object.id %}">
                                <button type="submit" class="btn btn-outline-danger">Удалить</button></a></td>
                        {% else %}
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    {# Пагинация #}
    {% include 'main/pagination.html' %}

    {# Добавление города #}
<!--    <div class="row">-->
<!--        <div class="col-md-4">-->
<!--            <form action="{% url 'cities:create' %}" method="post">-->
<!--            {% csrf_token %}-->
<!--            {{ form.as_p }}-->
<!--            <input type="submit" value="Добавить город">-->
<!--        </form>-->
<!--        </div>-->
<!--    </div>-->
{% endblock %}

cities/templates/cities/create.html
{% extends 'main/base.html' %}
{% block title %} Создание города {% endblock %}

{% block content %}
    <h3>Создание города</h3>

    {% include "main/form.html" with button="Добавить новый город" %}

{% endblock %}

cities/templates/cities/delete.html
{% extends 'main/base.html' %}
{% block title %} Удаление города {% endblock %}

{% block content %}
    <h3>Удаление города</h3>
    <p>{{ object }}</p>

    <div class="row">
        <div class="col-md-4">
            <tr>
                <td><form action="{{action}}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-danger">Да, удалить</button>
                    </form></td><br>
                <td>
                    <a href="{% url 'cities:cities' %}">
                        <button type="button" class="btn btn-outline-primary">Нет, не удалять</button>
                    </a>
                </td>
            </tr>
        </div>
    </div>

{% endblock %}

cities/templates/cities/detail.html
{% extends 'main/base.html' %}

{% block title %} Детали города {% endblock %}

{% block content %}
    <h3>Город</h3>
    <div class="row">
        <div class="col-md">
                <p>Название города: {{object.name}}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'cities:cities' %}">
                <button type="button" class="btn btn-outline-primary">Назад к списку</button>
            </a>
        </div>
    </div>

{% endblock %}

cities/templates/cities/details.html
{% extends 'main/base.html' %}

{% block title %} Детали города {% endblock %}

{% block content %}
    <h1>Город</h1>
    <div class="row">
        <div class="col-md">
                <p>Название города: {{object.name}}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'cities' %}">
                <button type="button" class="btn btn-light">Назад к списку</button>
            </a>
        </div>
    </div>

{% endblock %}

cities/templates/cities/update.html
{% extends 'main/base.html' %}
{% block title %} Редактирование города {% endblock %}

{% block content %}
    <h3>Редактирование города</h3>

    {% include "main/form.html" with button="Редактировать" %}

{% endblock %}