accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, registration_view

app_name = "accounts"

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('registration/', registration_view, name="registration"),
]

cities/urls.py
from django.urls import path, include
from . import views
from .views import *
# CityDetailView, CityCreateView, CityUpdateView, CityDeleteView, CityListView

app_name = "cities"

urlpatterns = [
    # path('', views.cities, name="cities"),
    path('', CityListView.as_view(), name="cities"),
    path('<int:pk>/', CityDetailView.as_view(), name="detail"),
    path('create/', CityCreateView.as_view(), name="create"),
    path('<int:pk>/update/', CityUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', CityDeleteView.as_view(), name="delete"),
]

find_route/urls.py
from django.contrib import admin
from django.urls import path, include

from routes.views import (
    home, find_routes, add_route, save_route, RoutesViewList, RouteDetailView
)


urlpatterns = [
    path('admin/', admin.site.urls),

    # path('', include('main.urls')),
    path('cities/', include('cities.urls')),
    path('trains/', include('trains.urls')),
    path('accounts/', include('accounts.urls')),
    # path('routes/', include('routes.urls')),
    path('', home, name='home'),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('save_route/', save_route, name='save_route'),
    path('list_routes/', RoutesViewList.as_view(), name='list_routes'),
    path('detail_route/<int:pk>/', RouteDetailView.as_view(), name='detail_route'),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
]

trains/urls.py
from django.urls import path, include
from . import views
from .views import *
# TrainListView, TrainDetailView, TrainCreateView, TrainUpdateView, TrainDeleteView

app_name = "trains"

urlpatterns = [
    path('', TrainListView.as_view(), name="trains"),
    path('<int:pk>/', TrainDetailView.as_view(), name="detail"),
    path('create/', TrainCreateView.as_view(), name="create"),
    path('<int:pk>/update/', TrainUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', TrainDeleteView.as_view(), name="delete"),
    # path('', views.trains, name="trains"),
]

main/views.py
from django.shortcuts import render


def home(request):
    data = {
        "title": "Cities",
    }

    return render(request, "main/home.html", data)

main/templates/main/base.html
{% url 'cities:cities' as cities_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'trains:trains' as trains_url %}
{% url 'trains:create' as trains_create_url %}
<!--<!doctype html>-->
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {# Навигационная панель шапки #}
    {% include 'main/nav.html' %}

    {# Сообщение о совершении действия/ ошибке #}
    {% include 'main/message.html' %}

    {# Блок с основным контентом страницы #}
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {# Дополнительные функции/ скрипты от Bootstrap #}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('.js-example-basic-single').select2();
            $('.js-example-basic-multiple').select2();
        });
    </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
</body>
</html>

main/templates/main/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{action}}" method="post">  {# enctype="multipart/form-data" #}
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-primary">{{ button }}</button>
        </form>
    </div>
</div>

main/templates/main/message.html
{# Сообщение о совершении действия/ ошибке #}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

main/templates/main/nav.html
{# Навигационная панель шапки #}
<nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Маршрут-ка</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == cities_url %}active{% endif %}"
                       aria-current="page" href="{% url 'cities:cities' %}">Города</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == trains_url %}active{% endif %}"
                       aria-current="page" href="{% url 'trains:trains' %}">Поезда</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'list_routes' %}">Маршруты</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle
                                      {% if request.path == cities_create_url or request.path == trains_create_url %}
                                        active
                                      {% endif %}
                                     " href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                          Добавить
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <li><a class="dropdown-item" href="{% url 'cities:create' %}">Новый город</a></li>
                          <li><a class="dropdown-item" href="{% url 'trains:create' %}">Новый поезд</a></li>
                          <li><a class="dropdown-item" href="{% url 'home' %}">Новый маршрут</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Добавить</a></li>
                {% endif %}
                {# Авторизация/ выход пользователя #}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link disabled" style="color: black;" href="#">Вы вошли как: {{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:registration' %}">Зарегистрироваться</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

main/templates/main/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            {% endif %}
        </li>
            {% for page in page_obj.paginator.page_range %}
                <li class="page-item {% if page == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{page}}">{{page}}</a>
                </li>
            {% endfor %}
        <li class="page-item">
            {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            {% endif %}
        </li>
    </ul>
</nav>